version: '3'

networks: 
    dashboard_network:
        external: true

services: 
    dashboard_acl_frontend:
        hostname: dashboard_acl_frontend
        container_name: dashboard_acl_frontend
        image: dashboard_acl_frontend:latest
        environment: 
            VUE_APP_BACKEND_URL: dashboard_acl_backend/
            VUE_APP_KEYCLOAK_URL: https://ireceptorplus.inesctec.pt/auth/
            VUE_APP_KEYCLOAK_REALM: iReceptorPlus
        networks: 
            - dashboard_network
        ports: 
            - 9091:8080
        restart: always